// Publication playbooks: which graphics and channel variants one communication event needs,
// when to publish them and which confirmed facts they require. Isomorphic (shared with the browser).
import { postTypes } from '../post-types.js';

export const PLAYBOOK_VERSION = '1.0.0';

const IG = (graphic = 'main', format = 'feed') => ({ graphic, format });
const STORY = (graphic = 'main') => ({ graphic, format: 'story' });
const FB = (graphic = 'main', format = 'feed') => ({ graphic, format });
const WWW = (graphic = 'main', format = 'landscape') => ({ graphic, format });
const portraitWWW = (graphic = 'main') => WWW(graphic, 'feed');

// `hint` is the editorial schema of the playbook: what every variant must say. Prompts reuse it.
export const playbooks = [
  {
    id: 'match-preview',
    category: 'Mecz',
    label: 'Zapowiedź meczu',
    timing: '2–3 dni przed meczem',
    offsetHours: -60,
    factsKind: 'match',
    required: ['opponent', 'date', 'venue'],
    graphics: { main: { postType: 'preview', formats: ['feed', 'story', 'landscape'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB() },
    hint: 'Kiedy, gdzie i z kim gramy. Kolejka KALK. „Wstęp wolny”, jeśli potwierdzony. Zaproszenie bez patosu.',
  },
  {
    id: 'matchday',
    category: 'Mecz',
    label: 'Dzień meczu',
    timing: 'rano w dniu meczu',
    offsetHours: -8,
    factsKind: 'match',
    required: ['opponent', 'date', 'venue'],
    graphics: { main: { postType: 'matchday', formats: ['story', 'feed'] } },
    items: { instagram_story: STORY(), facebook: FB() },
    hint: 'Krótko: dziś gramy, godzina, hala. Jedno zdanie zachęty.',
  },
  {
    id: 'match-live',
    category: 'Mecz',
    label: 'Wynik na żywo / przerwa',
    timing: 'w trakcie meczu',
    offsetHours: 1,
    factsKind: 'match',
    required: ['opponent', 'scoreUs', 'scoreThem'],
    graphics: { main: { postType: 'halftime', formats: ['story'] } },
    items: { instagram_story: STORY() },
    hint: 'Aktualny wynik i faza meczu wpisane ręcznie. Bez ocen i przewidywań.',
  },
  {
    id: 'match-result',
    category: 'Mecz',
    label: 'Wynik meczu',
    timing: 'wieczorem po meczu',
    offsetHours: 3,
    factsKind: 'match',
    required: ['opponent', 'scoreUs', 'scoreThem'],
    graphics: { main: { postType: 'final', formats: ['feed', 'story', 'landscape'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB(), website: WWW() },
    hint: 'Wynik (BeKaPaKa pierwsza), kolejka, 1–2 liderów z danych KALK, następny mecz jeśli znany. Porażka rzeczowo, bez dramatyzmu.',
  },
  {
    id: 'match-report',
    category: 'Mecz',
    label: 'Relacja z meczu',
    timing: 'dzień po meczu',
    offsetHours: 20,
    factsKind: 'match',
    required: ['opponent', 'scoreUs', 'scoreThem'],
    graphics: {
      main: { postType: 'carousel', formats: ['feed'] },
      cover: { postType: 'report-cover', formats: ['story', 'feed'] },
    },
    items: { instagram_feed: IG(), instagram_story: STORY('cover'), facebook: FB(), website: portraitWWW('cover') },
    hint: 'Przebieg meczu w 3–4 krokach, sekcja „Mecz w liczbach”, liderzy, zdjęcia z prawami do publikacji. Artykuł na stronie jest źródłem, social prowadzi do niego.',
  },
  {
    id: 'mvp',
    category: 'Drużyna',
    label: 'MVP meczu',
    timing: '1–2 dni po meczu',
    offsetHours: 30,
    factsKind: 'player',
    required: ['person'],
    graphics: { main: { postType: 'mvp', formats: ['feed', 'story'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB() },
    hint: 'Potwierdzony wybór MVP, do 3 statystyk z meczu, rywal i wynik. Uznanie bez superlatywów.',
  },
  {
    id: 'match-leaders',
    category: 'Statystyki',
    label: 'Liderzy meczu',
    timing: '1–2 dni po meczu',
    offsetHours: 30,
    factsKind: 'statistics',
    required: ['opponent'],
    graphics: { main: { postType: 'leaders', formats: ['feed', 'story'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB() },
    hint: 'Liderzy w punktach, zbiórkach i asystach z publicznych danych KALK. Remisy wymieniamy wszystkie.',
  },
  {
    id: 'round-standings',
    category: 'Statystyki',
    label: 'Kolejka i tabela',
    timing: 'po zakończeniu kolejki',
    offsetHours: 48,
    factsKind: 'statistics',
    required: ['round'],
    graphics: { main: { postType: 'standings', formats: ['feed', 'story'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB(), website: portraitWWW() },
    hint: 'Miejsce BeKaPaKa w tabeli po kolejce, bilans, najbliższy rywal. Dane z KALK, stan na dzień publikacji.',
  },
  {
    id: 'schedule',
    category: 'Informacje',
    label: 'Terminarz',
    timing: 'na początku miesiąca',
    offsetHours: 0,
    factsKind: 'manual',
    required: ['title'],
    graphics: { main: { postType: 'schedule', formats: ['feed', 'story', 'landscape'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB() },
    hint: 'Lista najbliższych meczów: data, godzina, rywal. Wszystkie mecze KALK w KOSiR Koszalin. „Wstęp wolny”.',
  },
  {
    id: 'postponed',
    category: 'Mecz',
    label: 'Mecz przełożony',
    timing: 'niezwłocznie',
    offsetHours: 0,
    factsKind: 'match',
    required: ['opponent', 'originalDate'],
    graphics: { main: { postType: 'postponed', formats: ['feed', 'story', 'landscape'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB(), website: WWW() },
    hint: 'Poprzedni i nowy termin (jeśli znany). Powód tylko publiczny i potwierdzony.',
  },
  {
    id: 'cancelled',
    category: 'Mecz',
    label: 'Mecz odwołany',
    timing: 'niezwłocznie',
    offsetHours: 0,
    factsKind: 'match',
    required: ['opponent', 'date'],
    graphics: { main: { postType: 'cancelled', formats: ['feed', 'story', 'landscape'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB(), website: WWW() },
    hint: 'Który mecz jest odwołany. Bez spekulacji o przyczynach.',
  },
  {
    id: 'tournament-preview',
    category: 'Turniej',
    label: 'Zapowiedź turnieju',
    timing: '2 tygodnie przed',
    offsetHours: -336,
    factsKind: 'tournament',
    required: ['title', 'date', 'venue'],
    graphics: { main: { postType: 'tournament-preview', formats: ['feed', 'story', 'landscape'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB(), website: WWW() },
    hint: 'Edycja (cyframi rzymskimi), data, CESiR Bobolice, liczba drużyn, zaproszenie dla mieszkańców.',
  },
  {
    id: 'tournament-program',
    category: 'Turniej',
    label: 'Program turnieju',
    timing: '2–3 dni przed',
    offsetHours: -60,
    factsKind: 'tournament',
    required: ['title', 'date'],
    graphics: { main: { postType: 'tournament-program', formats: ['feed', 'story', 'landscape'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB() },
    hint: 'Godziny meczów i ceremonii. Tylko potwierdzony program.',
  },
  {
    id: 'tournament-summary',
    category: 'Turniej',
    label: 'Podsumowanie turnieju',
    timing: 'dzień po',
    offsetHours: 20,
    factsKind: 'tournament',
    required: ['title'],
    graphics: { main: { postType: 'tournament-summary', formats: ['feed', 'story', 'landscape'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB(), website: WWW() },
    hint: 'Klasyfikacja końcowa, „Turniej w liczbach”, podziękowania partnerom (równo, alfabetycznie).',
  },
  {
    id: 'player-profile',
    category: 'Drużyna',
    label: 'Prezentacja zawodnika',
    timing: 'dowolnie',
    offsetHours: 0,
    factsKind: 'player',
    required: ['person'],
    graphics: { main: { postType: 'profile', formats: ['feed', 'story'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB() },
    hint: 'Imię i nazwisko, numer, pozycja. Wizerunek tylko za zgodą.',
  },
  {
    id: 'new-player',
    category: 'Drużyna',
    label: 'Nowy zawodnik',
    timing: 'po potwierdzeniu transferu',
    offsetHours: 0,
    factsKind: 'player',
    required: ['person'],
    graphics: { main: { postType: 'new-player', formats: ['feed', 'story'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB(), website: portraitWWW() },
    hint: 'Kto dołącza, numer, pozycja. Powitanie w drużynie, bez obietnic wyników.',
  },
  {
    id: 'partner-thanks',
    category: 'Partnerzy',
    label: 'Podziękowanie partnerom',
    timing: 'po wydarzeniu / sezonie',
    offsetHours: 0,
    factsKind: 'partner',
    required: ['title'],
    graphics: { main: { postType: 'partner-thanks', formats: ['feed', 'story'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB(), website: portraitWWW() },
    hint: 'Za co dziękujemy, konkretnie. Partnerzy alfabetycznie, równa ekspozycja, bez hierarchii.',
  },
  {
    id: 'partner-profile',
    category: 'Partnerzy',
    label: 'Przedstawienie partnera',
    timing: 'dowolnie',
    offsetHours: 0,
    factsKind: 'partner',
    required: ['partner'],
    graphics: { main: { postType: 'partner-profile', formats: ['feed', 'story'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB() },
    hint: 'Kim jest partner i jak wspiera klub — tylko potwierdzone informacje, bez tekstu reklamowego.',
  },
  {
    id: 'partner-wall',
    category: 'Partnerzy',
    label: 'Partnerzy klubu',
    timing: 'początek sezonu',
    offsetHours: 0,
    factsKind: 'partner',
    required: [],
    graphics: { main: { postType: 'partner-wall', formats: ['feed', 'story'] } },
    items: { instagram_feed: IG(), facebook: FB(), website: portraitWWW() },
    hint: 'Wszyscy aktualni partnerzy, alfabetycznie, jednym poziomem.',
  },
  {
    id: 'birthday',
    category: 'Życie klubu',
    label: 'Urodziny',
    timing: 'w dniu urodzin',
    offsetHours: 0,
    factsKind: 'player',
    required: ['person'],
    graphics: { main: { postType: 'birthday', formats: ['feed', 'story'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB() },
    hint: 'Życzenia od drużyny. Bez wieku i danych prywatnych.',
  },
  {
    id: 'training',
    category: 'Życie klubu',
    label: 'Trening',
    timing: 'dzień przed',
    offsetHours: -24,
    factsKind: 'club',
    required: ['date', 'venue'],
    graphics: { main: { postType: 'training-preview', formats: ['story', 'feed'] } },
    items: { instagram_story: STORY(), facebook: FB() },
    hint: 'Kiedy i gdzie. Bez frekwencji i notatek trenera.',
  },
  {
    id: 'backstage',
    category: 'Życie klubu',
    label: 'Kulisy',
    timing: 'dowolnie',
    offsetHours: 0,
    factsKind: 'club',
    required: ['title'],
    graphics: { main: { postType: 'backstage', formats: ['feed', 'story'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB() },
    hint: 'Co widać na zdjęciu i kto na nim jest (za zgodą). Lokalnie, rodzinnie.',
  },
  {
    id: 'quote',
    category: 'Życie klubu',
    label: 'Cytat',
    timing: 'dowolnie',
    offsetHours: 0,
    factsKind: 'club',
    required: ['notes', 'person'],
    graphics: { main: { postType: 'quote', formats: ['feed', 'story'] } },
    items: { instagram_feed: IG(), facebook: FB() },
    hint: 'Dosłowny, autoryzowany cytat z autorem. Nigdy nie wymyślamy wypowiedzi.',
  },
  {
    id: 'anniversary',
    category: 'Życie klubu',
    label: 'Jubileusz',
    timing: 'w rocznicę',
    offsetHours: 0,
    factsKind: 'club',
    required: ['title', 'date'],
    graphics: { main: { postType: 'anniversary', formats: ['feed', 'story'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB(), website: portraitWWW() },
    hint: 'Co świętujemy i od kiedy. Podziękowanie społeczności.',
  },
  {
    id: 'fan-invitation',
    category: 'Życie klubu',
    label: 'Zaproszenie dla kibiców',
    timing: 'tydzień przed',
    offsetHours: -168,
    factsKind: 'club',
    required: ['title', 'date', 'venue'],
    graphics: { main: { postType: 'fan-invitation', formats: ['feed', 'story'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB(), website: portraitWWW() },
    hint: 'Na co zapraszamy, kiedy, gdzie. „Wstęp wolny”, jeśli dotyczy.',
  },
  {
    id: 'club-statement',
    category: 'Życie klubu',
    label: 'Komunikat klubu',
    timing: 'niezwłocznie',
    offsetHours: 0,
    factsKind: 'club',
    required: ['title', 'notes'],
    graphics: { main: { postType: 'club-statement', formats: ['feed', 'story'] } },
    items: { instagram_feed: IG(), facebook: FB(), website: portraitWWW() },
    hint: 'Treść komunikatu zatwierdzona przez zarząd. Bez dopisków i interpretacji.',
  },
  {
    id: 'news',
    category: 'Informacje',
    label: 'Aktualność',
    timing: 'dowolnie',
    offsetHours: 0,
    factsKind: 'manual',
    required: ['title'],
    graphics: { main: { postType: 'news', formats: ['feed', 'story', 'landscape'] } },
    items: { instagram_feed: IG(), facebook: FB(), website: WWW() },
    hint: 'Jedna informacja: co, kiedy, gdzie, dla kogo. Link do strony.',
  },
  {
    id: 'season-summary',
    category: 'Statystyki',
    label: 'Podsumowanie sezonu',
    timing: 'po ostatnim meczu sezonu',
    offsetHours: 72,
    factsKind: 'statistics',
    required: ['seasonLabel'],
    graphics: { main: { postType: 'season-summary', formats: ['feed', 'story'] } },
    items: { instagram_feed: IG(), instagram_story: STORY(), facebook: FB(), website: portraitWWW() },
    hint: '„Sezon w liczbach”: mecze, bilans, punkty. Podziękowania drużynie, kibicom i partnerom.',
  },
];

export const playbook = (id) => playbooks.find((p) => p.id === id);
export const playbookCategories = [...new Set(playbooks.map((p) => p.category))];

// Graphics of a playbook are ordinary Studio projects; a format must exist for the composition.
export function graphicFormats(definition) {
  const type = postTypes.find((t) => t.id === definition.postType);
  return definition.formats.filter((f) => type?.formats.includes(f));
}
