import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, Check, Copy, Download, Eye, History, LoaderCircle, Monitor, RefreshCw, ShieldCheck, Smartphone, Sparkles, Undo2, X } from 'lucide-react';
import { api, send, fileUrl, ApiError } from './api';
import { formats, projectSchema, visualStyles } from '../../backend/studio/contracts.js';
import { migrateDesign, DESIGN_VERSION, designFormats, compositionLabel, projectTemplateVersion } from '../../backend/studio/post-types.js';
import { materialCompatible } from '../../backend/studio/material-context.js';
import { weekday, warsawInput, warsawIso } from './dates';
import { initialSeason, type Season } from './seasons';
import type { Project, View, Template, Asset, Partner, Budget, Job, Report, PostType } from './types';
import ExportFile from './ExportFile';
import StatisticsImport from './StatisticsImport';
import SocialPreview, { PreviewOptions, type PreviewPlatform } from './SocialPreview';
const labels: Record<string, string> = { standard: 'Zapowiedź', matchday: 'Dzień meczu', postponed: 'Przełożony', cancelled: 'Odwołany', final: 'Koniec meczu', halftime: 'Przerwa', live: 'Na żywo', five: 'Pierwsza piątka', full: 'Pełny skład', profile: 'Prezentacja', new: 'Nowy zawodnik', mvp: 'MVP', announcement: 'Zapowiedź', program: 'Program', summary: 'Podsumowanie', cover: 'Okładka', photo: 'Fotograficzny', carousel: 'Karuzela 4 slajdy', wall: 'Zbiorcza plansza', spotlight: 'Przedstawienie', thanks: 'Podziękowanie', schedule: 'Terminarz', notice: 'Ogłoszenie', news: 'Aktualność', marks: 'Znaki drużyn', type: 'Typograficzny', board: 'Tablica wyniku', jerseys: 'Koszulki', poster: 'Plakat turnieju', editorial: 'Zdjęcie i treść', tiles: 'Kafle partnerów', paper: 'Papier' };
type SourceItem = { id: string; seasonId?: string; name?: string; title?: string; date?: string; opponent?: string; firstName?: string; lastName?: string; number?: string; position?: string };
export default function Editor({ initial, posts, templates, assets, partners, budget, reloadLibrary, onClose, onDuplicate }: { initial: View; posts: PostType[]; templates: Template[]; assets: Asset[]; partners: Partner[]; budget: Budget | null; reloadLibrary: () => Promise<void>; onClose: () => void; onDuplicate: () => Promise<void> }) {
  const [view, setView] = useState(initial); const [project, setProject] = useState<Project>(projectSchema.parse(initial.payload)); const [saved, setSaved] = useState('Zapisano');
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [preview, setPreview] = useState<Job | null>(null); const [format, setFormat] = useState(initial.payload.formats[0]);
  const [job, setJob] = useState<Job | null>(null); const [report, setReport] = useState<Report | null>(null); const [mobileStep, setMobileStep] = useState('edit'); const [phone, setPhone] = useState(false); const [fullscreen, setFullscreen] = useState(false); const [slide, setSlide] = useState(0);
  const [platform, setPlatform] = useState<PreviewPlatform>('artwork'); const [safeZones, setSafeZones] = useState(false);
  const [history, setHistory] = useState<{ number: number; payload: Project; createdAt: string }[] | null>(null); const [undo, setUndo] = useState<Project[]>([]);
  const [sourceKind, setSourceKind] = useState<string>(['match','player','event','news'].includes(initial.payload.content.source.kind)?initial.payload.content.source.kind:initial.payload.family==='player'||initial.payload.variant==='birthday'?'player':initial.payload.family==='tournament'?'event':initial.payload.family==='club'?'news':'match'); const [season, setSeason] = useState(''); const [seasons, setSeasons] = useState<Season[]>([]); const [sourceItems, setSourceItems] = useState<SourceItem[]>([]);
  const [players, setPlayers] = useState<SourceItem[]>([]); const [sourceDiff, setSourceDiff] = useState<{ data: Record<string, unknown>; source: Project['content']['source'] } | null>(null);
  const [approvalOpen, setApprovalOpen] = useState(false); const [aiResult, setAiResult] = useState<Job | null>(null); const [brief, setBrief] = useState('texture');
  const latest = useRef(project); latest.current = project; const server = useRef(initial); const saving = useRef<Promise<View> | null>(null); const mounted = useRef(true);
  const t = templates.find(t => t.id === project.family)!; const publication=posts.find(p=>p.id===project.postType); const designApproved=(f:string)=>project.designVersion===DESIGN_VERSION && publication?.designs?.some(d=>d.style===project.visualStyle&&d.format===f&&d.kit===project.content.kit&&d.backgroundAssetId===(project.content.backgroundAssetId || null)&&d.status==='approved') || false; const templateStatus=project.postType ? (project.formats.every(designApproved)?'approved':'draft') : 'draft'; const d = project.content; const readonly = view.status === 'archived';
  function change(next: Project) { if(!next.formats.includes(format)) setFormat(next.formats[0]); setUndo(u => [...u.slice(-39), latest.current]); setProject(next); setReport(null); }
  function field(key: keyof Project['content'], value: unknown) { change({ ...latest.current, content: { ...latest.current.content, [key]: value } }); }
  async function flush(): Promise<View> {
    if (saving.current) { await saving.current; return flush(); }
    if (JSON.stringify(latest.current) === JSON.stringify(server.current.payload) && (latest.current.designVersion!==DESIGN_VERSION || server.current.revision.templateVersion===projectTemplateVersion(latest.current))) return server.current;
    const parsed = projectSchema.safeParse(latest.current);
    if (!parsed.success) { const msg = parsed.error.issues.map(i => `${i.path.join('.')}: ${i.message}`).join('; '); setSaved('Popraw pola'); throw new Error(msg); }
    const canonical = parsed.data; latest.current = canonical; setProject(canonical);
    setSaved('Zapisywanie…');
    const promise = send<View>(`/projects/${initial.id}`, { expectedRevision: server.current.currentRevision, project: parsed.data }, 'PUT'); saving.current = promise;
    try { const v = await promise; server.current = v; if (mounted.current) { setView(v); setSaved('Zapisano'); } }
    catch (err) { if (mounted.current) { setSaved(err instanceof ApiError && err.status === 409 ? 'Konflikt edycji' : 'Nie zapisano'); setError((err as Error).message); } throw err; }
    finally { saving.current = null; }
    if (JSON.stringify(latest.current) !== JSON.stringify(server.current.payload)) return flush();
    return server.current;
  }
  useEffect(() => { mounted.current = true; const guard = (e: BeforeUnloadEvent) => { if (JSON.stringify(latest.current) !== JSON.stringify(server.current.payload)) { e.preventDefault(); e.returnValue = ''; } }; window.addEventListener('beforeunload', guard); return () => { mounted.current = false; window.removeEventListener('beforeunload', guard); }; }, []);
  useEffect(() => { if (readonly) return; const timer = window.setTimeout(() => void flush().catch(() => {}), 900); return () => window.clearTimeout(timer); }, [project]);
  useEffect(() => { api<Season[]>('/sources/seasons').then(s => { setSeasons(s); setSeason(initialSeason(s, initial.payload.content.source.seasonId)); }).catch(() => {}); api<SourceItem[]>('/sources/players').then(setPlayers).catch(() => {}); }, []);
  useEffect(() => { let active = true; if (sourceKind === 'match' && !season) return; const url = sourceKind === 'match' ? `/sources/matches?seasonId=${encodeURIComponent(season)}` : sourceKind === 'player' ? '/sources/players' : `/sources/cms/${sourceKind}`; api<SourceItem[]>(url).then(s => { if (active) setSourceItems(s); }).catch(() => { if (active) setSourceItems([]); }); return () => { active = false; }; }, [sourceKind, season]);
  useEffect(() => {
    let active = true;
    if (readonly) {
      // Archived projects cannot queue renders; show the newest stored preview instead of an endless loader.
      setPreview(null); setSlide(0);
      api<Job | null>(`/projects/${initial.id}/preview?format=${encodeURIComponent(format)}`).then(j => { if (active) setPreview(j); }).catch(err => { if (active) setError(err.message); });
      return () => { active = false; };
    }
    const timer = window.setTimeout(() => { send<Job>(`/projects/${initial.id}/jobs`, { kind: 'preview', format }).then(j => { if (active) { setPreview(j); setSlide(0); } }).catch(err => { if (active) setError(err.message); }); }, 600);
    return () => { active = false; window.clearTimeout(timer); };
  }, [view.currentRevision, format, readonly]);
  useEffect(() => { if (!preview || !['queued', 'running'].includes(preview.status)) return; const timer = window.setTimeout(() => { api<Job>(`/jobs/${preview.id}`).then(j => setPreview(p => p?.id === j.id ? j : p)).catch(err => setError(err.message)); }, 1200); return () => window.clearTimeout(timer); }, [preview]);
  useEffect(() => { if (!job || !['queued', 'running'].includes(job.status)) return; const timer = window.setTimeout(() => { api<Job>(`/jobs/${job.id}`).then(j => { setJob(j); if (j.status === 'completed' && j.kind === 'ai-text') setAiResult(j); if (!['queued', 'running'].includes(j.status) && j.kind.startsWith('ai-')) void reloadLibrary(); }).catch(err => setError(err.message)); }, 1500); return () => window.clearTimeout(timer); }, [job]);
  useEffect(() => {
    if (d.source.kind === 'manual' || !d.source.id) return;
    let active = true;
    const checkSource = async () => {
      try { const result = await api<typeof sourceDiff>(`/sources/snapshot?kind=${d.source.kind}&id=${encodeURIComponent(d.source.id)}&seasonId=${encodeURIComponent(d.source.seasonId)}&subjectId=${encodeURIComponent(d.source.subjectId || '')}&view=${encodeURIComponent(d.source.view || 'team')}`); if (active && result && result.source.hash !== d.source.hash) setSourceDiff(result); } catch { /* Source outage leaves the saved snapshot usable. */ }
    };
    void checkSource(); const timer = window.setInterval(checkSource, 60_000);
    return () => { active = false; window.clearInterval(timer); };
  }, [d.source.kind, d.source.id, d.source.hash]);
  async function action(fn: () => Promise<void>) { setBusy(true); setError(''); try { await flush(); await fn(); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }
  async function validate() { const v = await api<Report>(`/projects/${initial.id}/validation`); setReport(v); return v; }
  async function restore() { await action(async () => { const v = await send<View>(`/projects/${initial.id}/restore`, { confirmed: true }); server.current = v; latest.current = v.payload; setProject(v.payload); setView(v); setSaved('Zapisano'); }); }
  async function importSource(id: string) {
    await action(async () => { const result = await api<{ data: Record<string, unknown>; source: Project['content']['source'] }>(`/sources/snapshot?kind=${sourceKind}&id=${encodeURIComponent(id)}&seasonId=${encodeURIComponent(season)}`); applySource(result); });
  }
  function applySource(result: { data: Record<string, unknown>; source: Project['content']['source'] }) {
    const content = { ...latest.current.content }; for (const key of ['opponent', 'date', 'venue', 'scoreUs', 'scoreThem', 'firstName', 'lastName', 'number', 'position', 'statistics', 'title', 'body', 'tableRows', 'statScope', 'attribution']) if (key in result.data && result.data[key] != null) (content as Record<string, unknown>)[key] = result.data[key];
    if (result.source.kind === 'player') content.statistics = [];
    content.references = [...content.references.filter(r => r.kind !== result.source.kind), result.source].slice(-5);
    if (!(result.source.kind === 'player' && content.source.kind === 'match' && project.family === 'player')) content.source = result.source; content.mvpConfirmed = false; content.lineupConfirmed = false; change({ ...latest.current, content }); setSourceDiff(null);
  }
  const input = (key: keyof Project['content'], label: string, opts: { type?: string; maxLength?: number; area?: boolean } = {}) => <label key={key}>{label}{opts.area ? <textarea value={String(d[key] ?? '')} maxLength={opts.maxLength || 1500} onChange={e => field(key, e.target.value)} disabled={readonly}/> : <input value={String(d[key] ?? '')} type={opts.type || 'text'} maxLength={opts.maxLength || 180} onChange={e => field(key, opts.type === 'number' ? (e.target.value === '' ? null : Number(e.target.value)) : e.target.value)} disabled={readonly}/>}</label>;
  const dateInput = (key: 'date' | 'originalDate', label: string) => <label>{label}<input type="datetime-local" value={warsawInput(d[key])} disabled={readonly} onChange={e => { try { field(key, warsawIso(e.target.value)); } catch (err) { setError((err as Error).message); } }}/><small>{key === 'date' ? weekday(d[key]) : 'Czas w Polsce'}</small></label>;
  const toggle = (key: 'kitBConfirmed' | 'lineupConfirmed' | 'mvpConfirmed', label: string) => <label className="check-label"><input type="checkbox" checked={d[key]} onChange={e => field(key, e.target.checked)} disabled={readonly}/>{label}</label>;
  const photoOptions = assets.filter(a => ['photo', 'portrait', 'cutout'].includes(a.kind) && a.status !== 'retired');
  const imageSelect = (key: 'photoAssetId' | 'backgroundAssetId', label: string) => <label>{label}<select value={d[key] || ''} onChange={e => field(key, e.target.value || null)} disabled={readonly}><option value="">{key === 'backgroundAssetId' ? 'Materiał z pakietu marki' : 'Wybierz z biblioteki'}</option>{(key === 'backgroundAssetId' ? assets.filter(a => a.kind === 'background' && a.status !== 'retired') : photoOptions).map(a => <option key={a.id} value={a.id}>{a.name}{key==='backgroundAssetId' && !materialCompatible(project,a) ? ' · inny kontekst' : ''}{a.status !== 'approved' ? ' · do sprawdzenia' : ''}</option>)}</select></label>;
  useEffect(() => { if (!fullscreen) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setFullscreen(false); }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [fullscreen]);
  const outputs = preview?.result?.files || []; const image = outputs[slide]; const currentPreview = preview?.status === 'completed' && preview.revision === view.currentRevision && saved === 'Zapisano';
  const previewOptions = <PreviewOptions platform={platform} onPlatform={setPlatform} safeZones={safeZones} onSafeZones={setSafeZones} story={format === 'story'}/>;
  const previewImage = image && <SocialPreview src={fileUrl(preview!.id, image.key)} alt={d.altText || 'Roboczy podgląd grafiki'} format={format} platform={platform} safeZones={safeZones} caption={d.caption} stale={!currentPreview} phone={phone}/>;
  return <>
    <header className="editor-header"><button className="icon-button" aria-label="Wróć do projektów" disabled={busy} onClick={() => void action(async () => onClose())}><ArrowLeft size={20}/></button><div><input className="project-name" aria-label="Nazwa projektu" value={project.name} maxLength={180} onChange={e => change({ ...project, name: e.target.value })} disabled={readonly}/><span className="save-status">{saved === 'Zapisano' ? <Check size={12}/> : <LoaderCircle size={12}/>} {readonly ? 'Projekt zarchiwizowany' : saved} · rewizja {view.currentRevision}</span></div><div className="editor-tools"><button className="icon-button" aria-label="Cofnij" title="Cofnij" disabled={!undo.length || readonly} onClick={() => { const previous = undo.at(-1)!; setUndo(u => u.slice(0, -1)); setProject(previous); }}><Undo2 size={18}/></button><button className="icon-button" aria-label="Historia" title="Historia" onClick={() => void action(async () => setHistory(await api(`/projects/${initial.id}/revisions`)))}><History size={18}/></button><button className="icon-button" aria-label="Duplikuj" title="Duplikuj" onClick={() => void action(onDuplicate)}><Copy size={18}/></button><button className="primary" disabled={busy || readonly} onClick={() => { setMobileStep('export'); void action(async () => { await validate(); }); }}><Download size={17}/><span>Eksport</span></button></div></header>
    {error && <div className="editor-error" role="alert"><p>{error}</p><button onClick={() => setError('')}>Zamknij</button>{saved === 'Konflikt edycji' && <button onClick={async () => { const v = await api<View>(`/projects/${initial.id}`); server.current = v; setView(v); setProject(v.payload); setError(''); setSaved('Zapisano'); }}>Wczytaj aktualną rewizję (odrzuć niezapisane zmiany)</button>}</div>}
    <div className="mobile-tabs">{[['edit', '1. Dane'], ['preview', '2. Podgląd'], ['export', '3. Eksport']].map(([id, label]) => <button className={mobileStep === id ? 'active' : ''} key={id} onClick={() => setMobileStep(id)}>{label}</button>)}</div>
    {readonly && <div className="editor-error archived-banner" role="status"><p>Projekt jest zarchiwizowany — edycja, podgląd i eksport są wyłączone.</p><button disabled={busy} onClick={() => void restore()}>Przywróć z archiwum</button><button disabled={busy} onClick={() => void action(onDuplicate)}>Utwórz kopię</button></div>}
    {project.designVersion!==DESIGN_VERSION && <div className="editor-error" role="status"><p>Historyczna kompozycja. Zachowujemy jej wygląd; nowe eksporty wymagają bieżącego szablonu.</p><button disabled={busy || readonly} onClick={()=>change(migrateDesign(project) as Project)}>Przenieś do nowej kompozycji · zachowaj poprzednią rewizję</button></div>}
    <div className={`editor-grid step-${mobileStep}`}>
      <section className="editor-form"><div className="panel-heading"><span className="eyebrow">TREŚĆ I MATERIAŁY</span><h2>{publication?.label || t.label}</h2></div>
        {project.family==='statistics' ? <StatisticsImport variant={project.variant} seasons={seasons} season={season} setSeason={setSeason} disabled={busy || readonly} importData={result=>action(async()=>applySource(result))}/> : <details open><summary>Dane z systemu</summary><div className="form-group"><div className="field-row"><label>Źródło<select value={sourceKind} onChange={e => setSourceKind(e.target.value)}><option value="match">Mecz</option><option value="player">Zawodnik</option><option value="event">Wydarzenie CMS</option><option value="news">Aktualność CMS</option></select></label>{sourceKind === 'match' && <label>Sezon<select value={season} onChange={e => setSeason(e.target.value)}>{seasons.map(s => <option key={s.id} value={s.id}>{s.label}</option>)}</select></label>}</div><label>Wybierz dane<select value="" onChange={e => e.target.value && void importSource(e.target.value)} disabled={busy || readonly}><option value="">{sourceItems.length ? 'Wybierz pozycję…' : 'Brak dostępnych danych'}</option>{sourceItems.map(s => <option key={s.id} value={s.id}>{s.opponent ? `${s.date?.slice(0, 10)} · ${s.opponent}` : s.title || `${s.firstName} ${s.lastName}`}</option>)}</select></label>{d.source.kind !== 'manual' && <div className="source-note"><span>Źródło: {d.source.kind} · {d.source.seasonId}<br/>Dane zapisane w projekcie, korekty pozostają lokalne.</span><button className="text-button" onClick={() => void action(async () => { const result = await api<typeof sourceDiff>(`/sources/snapshot?kind=${d.source.kind}&id=${encodeURIComponent(d.source.id)}&seasonId=${encodeURIComponent(d.source.seasonId)}&subjectId=${encodeURIComponent(d.source.subjectId || '')}&view=${encodeURIComponent(d.source.view || 'team')}`); if (result?.source.hash === d.source.hash) setError('Źródło nie zmieniło się od importu.'); else setSourceDiff(result); })}>Sprawdź zmiany <RefreshCw size={13}/></button></div>}</div></details>}
        {project.family==='statistics' && d.source.kind!=='manual' && <button className="text-button" onClick={()=>void action(async()=>{const r=await api<NonNullable<typeof sourceDiff>>(`/sources/snapshot?kind=${d.source.kind}&id=${encodeURIComponent(d.source.id)}&seasonId=${encodeURIComponent(d.source.seasonId)}&subjectId=${encodeURIComponent(d.source.subjectId || '')}&view=${encodeURIComponent(d.source.view || 'team')}`);if(r.source.hash===d.source.hash)setError('Źródło nie zmieniło się od importu.');else setSourceDiff(r);})}>Sprawdź zmiany źródła</button>}
        <details open><summary>Kompozycja</summary><div className="form-group">{project.postType ? <div className="editor-compositions">{visualStyles.filter(style=>project.designVersion!==DESIGN_VERSION || publication?.styles.includes(style.id)).map(style=><button key={style.id} disabled={readonly} aria-pressed={project.visualStyle===style.id} onClick={()=>change({...project,visualStyle:style.id as Project['visualStyle'],formats:project.formats.filter(f=>!publication || designFormats(publication,style.id).includes(f))})}><img src={`/designs/${project.postType}-${style.id}.webp`} alt=""/>{compositionLabel(publication,style.id)}</button>)}</div> : <div className="field-row"><label>Wariant<select value={project.variant} disabled={readonly} onChange={e => change({ ...project, variant: e.target.value })}>{t.variants.map(v => <option key={v} value={v}>{labels[v] || v}</option>)}</select></label><label>Układ<select value={project.layout} disabled={readonly} onChange={e => change({ ...project, layout: e.target.value })}>{t.layouts.map(v => <option key={v} value={v}>{labels[v] || v}</option>)}</select></label></div>}<label>Kolorystyka stroju<select value={d.kit} onChange={e => field('kit', e.target.value)} disabled={readonly}><option value="A">A · czerń i czerwień</option><option value="B">B · granat i pomarańcz</option></select></label>{d.kit === 'B' && toggle('kitBConfirmed', 'To materiał związany ze strojem B')}{imageSelect('backgroundAssetId', 'Tło')}</div></details>
        <details open><summary>{['announcement', 'result', 'lineup'].includes(project.family) ? 'Mecz' : 'Treść materiału'}</summary><div className="form-group">
          {['announcement', 'result', 'lineup'].includes(project.family) && <>{input('opponent', 'Rywal', { maxLength: 100 })}{input('opponentShort', 'Skrót rywala na tarczy', { maxLength: 8 })}</>}
          {!['player', 'partners'].includes(project.family) && dateInput('date', 'Data i godzina · Europe/Warsaw')}
          {project.visualStyle==='jersey' && <>{input('lastName','Nazwisko na koszulce',{maxLength:80})}{input('number','Numer na koszulce',{maxLength:3})}</>}
          {project.family === 'announcement' && input('entryInfo', 'Wstęp / bilety · tylko potwierdzone informacje', { maxLength: 80 })}
          {project.variant === 'postponed' && dateInput('originalDate', 'Poprzedni termin')}
          {['announcement', 'result', 'tournament','club'].includes(project.family) && input('venue', 'Miejsce', { maxLength: 100 })}
          {project.family === 'result' && <><div className="score-inputs">{input('scoreUs', 'BeKaPaKa', { type: 'number' })}<b>:</b>{input('scoreThem', 'Rywal', { type: 'number' })}</div>{project.variant !== 'final' && <>{input('phase', 'Kwarta / stan meczu', { maxLength: 50 })}<p className="muted small">Wynik na żywo i w przerwie wpisujesz ręcznie. KALK nie jest źródłem live.</p></>}</>}
          {['tournament', 'report', 'schedule', 'partners','club','statistics'].includes(project.family) && input('title', 'Nagłówek', { maxLength: 180 })}
          {(['tournament', 'report', 'schedule','club','statistics'].includes(project.family) || (project.postType && project.family==='partners' && project.variant==='thanks')) && input('body', 'Treść', { area: true })}
          {project.family === 'tournament' && <div className="field-row three">{input('edition', 'Edycja', { type: 'number' })}{input('teams', 'Drużyny', { type: 'number' })}{input('days', 'Dni', { type: 'number' })}</div>}
          {project.family === 'club' && project.variant==='birthday' && <>{input('firstName','Imię',{maxLength:60})}{input('lastName','Nazwisko',{maxLength:80})}</>}{project.family === 'club' && project.variant==='quote' && input('attribution','Autor cytatu',{maxLength:100})}{project.family === 'player' && <>{input('firstName', 'Imię', { maxLength: 60 })}{input('lastName', 'Nazwisko', { maxLength: 80 })}<div className="field-row">{input('number', 'Numer', { maxLength: 3 })}{input('position', 'Pozycja', { maxLength: 40 })}</div>{project.variant === 'mvp' && toggle('mvpConfirmed', 'Potwierdzam wybór zawodnika MVP')}</>}
        </div></details>
        {project.family==='statistics' && <details open><summary>Dane do publikacji</summary><div className="form-group"><p className="muted small">Brak danych pozostaw pusty. Zero wpisz wyłącznie, gdy jest potwierdzone w źródle.</p><label>Kontekst<select value={d.statScope || 'match'} onChange={e=>field('statScope',e.target.value)} disabled={readonly}><option value="match">Konkretny mecz / kolejka</option><option value="season">Sezon</option></select></label>{(d.tableRows || []).map((row,i)=><div className="data-table-row" key={i}><input aria-label={`Etykieta ${i+1}`} placeholder="Zawodnik, drużyna lub statystyka" maxLength={100} value={row.label} disabled={readonly} onChange={e=>field('tableRows',(d.tableRows || []).map((r,j)=>i===j?{...r,label:e.target.value}:r))}/><input aria-label={`Wartość ${i+1}`} placeholder="Potwierdzona wartość" maxLength={80} value={row.value} disabled={readonly} onChange={e=>field('tableRows',(d.tableRows || []).map((r,j)=>i===j?{...r,value:e.target.value}:r))}/><input aria-label={`Szczegóły ${i+1}`} placeholder="Opis, bilans lub etykieta" maxLength={100} value={row.detail} disabled={readonly} onChange={e=>field('tableRows',(d.tableRows || []).map((r,j)=>i===j?{...r,detail:e.target.value}:r))}/><button className="text-button" disabled={readonly} onClick={()=>field('tableRows',(d.tableRows || []).filter((_,j)=>i!==j))}>Usuń wiersz</button></div>)}<button className="text-button" disabled={readonly || (d.tableRows?.length || 0)>=60} onClick={()=>field('tableRows',[...(d.tableRows || []),{label:'',value:'',detail:''}])}>+ Dodaj wiersz</button></div></details>}
        {project.family === 'player' && <details><summary>Wybrane statystyki</summary><div className="form-group"><p className="muted small">Wybierz do 3 liczb. PTS/REB/AST dotyczą meczu, PPG/RPG/APG — średniej sezonu. Potwierdź ich źródło przed eksportem.</p>{d.statistics.map((s, i) => <div className="list-editor" key={i}><select aria-label="Etykieta statystyki" value={s.label} onChange={e => field('statistics', d.statistics.map((x, j) => j === i ? { ...x, label: e.target.value } : x))}>{['PTS','REB','AST','PPG','RPG','APG'].map(v => <option key={v}>{v}</option>)}</select><input type="number" min="0" max="999" step="0.1" aria-label="Wartość statystyki" value={s.value} onChange={e => field('statistics', d.statistics.map((x, j) => j === i ? { ...x, value: Number(e.target.value) } : x))}/><button className="icon-button" aria-label="Usuń statystykę" onClick={() => field('statistics', d.statistics.filter((_, j) => j !== i))}><X size={15}/></button></div>)}{d.statistics.length < 3 && <button className="text-button" onClick={() => field('statistics', [...d.statistics, { label: 'PTS', value: 0 }])}>+ Dodaj statystykę</button>}</div></details>}
        {project.family === 'lineup' && <details open><summary>Skład meczowy</summary><div className="form-group"><label>Dodaj zawodnika<select value="" onChange={e => { const p = players.find(p => p.id === e.target.value); if (p && !d.lineup.some(x => x.id === p.id)) field('lineup', [...d.lineup, { id: p.id, firstName: p.firstName || '', lastName: p.lastName || '', number: p.number || '', position: p.position || '' }]); }} disabled={readonly}><option value="">Wybierz z rosteru…</option>{players.map(p => <option key={p.id} value={p.id}>{p.firstName} {p.lastName} · #{p.number}</option>)}</select></label>{d.lineup.map((p, i) => <div className="list-editor" key={i}><input aria-label={`Nazwisko ${i + 1}`} value={p.lastName} onChange={e => field('lineup', d.lineup.map((x, j) => j === i ? { ...x, lastName: e.target.value } : x))}/><input aria-label={`Numer ${i + 1}`} value={p.number} maxLength={3} onChange={e => field('lineup', d.lineup.map((x, j) => j === i ? { ...x, number: e.target.value } : x))}/><button className="icon-button" aria-label="Usuń zawodnika" onClick={() => field('lineup', d.lineup.filter((_, j) => j !== i))}><X size={15}/></button></div>)}<button className="text-button" disabled={readonly} onClick={() => field('lineup', [...d.lineup, { id: '', firstName: '', lastName: '', number: '', position: '' }])}>+ Dodaj ręcznie</button>{toggle('lineupConfirmed', 'Potwierdzam skład na ten konkretny mecz')}</div></details>}
        {project.family === 'schedule' && project.variant === 'schedule' && <details open><summary>Pozycje terminarza</summary><div className="form-group">{d.schedule.map((row, i) => <div className="schedule-editor" key={i}><label>Data<input type="datetime-local" value={warsawInput(row.date)} onChange={e => { try { field('schedule', d.schedule.map((r, j) => j === i ? { ...r, date: warsawIso(e.target.value) } : r)); } catch (err) { setError((err as Error).message); } }}/></label><div className="list-editor"><input aria-label="Rywal" placeholder="Rywal" value={row.opponent} onChange={e => field('schedule', d.schedule.map((r, j) => j === i ? { ...r, opponent: e.target.value } : r))}/><input aria-label="Kolejka" placeholder="Kolejka" value={row.round} onChange={e => field('schedule', d.schedule.map((r, j) => j === i ? { ...r, round: e.target.value } : r))}/><button className="icon-button" aria-label="Usuń pozycję" onClick={() => field('schedule', d.schedule.filter((_, j) => j !== i))}><X size={15}/></button></div></div>)}<button className="text-button" disabled={readonly} onClick={() => field('schedule', [...d.schedule, { date: '', opponent: '', round: '' }])}>+ Dodaj termin</button></div></details>}
        {project.family === 'report' && project.variant === 'carousel' && <details open><summary>Slajdy karuzeli</summary><div className="form-group">{d.slides.map((s, i) => <div className="schedule-editor" key={i}><div className="section-title"><b>Slajd {i + 1}</b><button className="text-button" onClick={() => { const slides = [...d.slides]; const other = i ? i - 1 : slides.length - 1; [slides[i], slides[other]] = [slides[other], slides[i]]; field('slides', slides); }}>Przesuń wcześniej</button></div><label>Tytuł<input value={s.title} onChange={e => field('slides', d.slides.map((x, j) => j === i ? { ...x, title: e.target.value } : x))}/></label><label>Treść<textarea value={s.body} maxLength={600} onChange={e => field('slides', d.slides.map((x, j) => j === i ? { ...x, body: e.target.value } : x))}/></label><label>Tekst alternatywny slajdu<textarea value={s.altText} maxLength={1500} onChange={e => field('slides', d.slides.map((x, j) => j === i ? { ...x, altText: e.target.value } : x))}/></label><label>Zdjęcie<select value={s.assetId || ''} onChange={e => field('slides', d.slides.map((x, j) => j === i ? { ...x, assetId: e.target.value || null } : x))}><option value="">Wybierz materiał</option>{photoOptions.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button className="text-button" onClick={() => field('slides', d.slides.filter((_, j) => j !== i))}>Usuń slajd</button></div>)}{d.slides.length < 4 && <button className="text-button" onClick={() => field('slides', [...d.slides, { title: '', body: '', altText: '', assetId: null }])}>+ Dodaj slajd</button>}</div></details>}
        {project.family === 'partners' && <details open><summary>Wybór partnerów</summary><div className="form-group">{partners.filter(p => p.status !== 'retired').map(p => <label className="check-label" key={p.id}><input type="checkbox" checked={d.partnerIds.includes(p.id)} disabled={readonly} onChange={e => field('partnerIds', e.target.checked ? [...d.partnerIds, p.id] : d.partnerIds.filter(id => id !== p.id))}/>{p.name}{p.status !== 'approved' && <small>do sprawdzenia</small>}</label>)}</div></details>}
        {(project.postType || ['result', 'player', 'report'].includes(project.family)) && <details open><summary>Zdjęcie i kadrowanie</summary><div className="form-group">{imageSelect('photoAssetId', 'Zdjęcie')}{(['x', 'y', 'zoom'] as const).map(k => <label key={k}>{({ x: 'Kadr poziomo', y: 'Kadr pionowo', zoom: 'Skala' })[k]}<input type="range" min={k === 'zoom' ? 1 : 0} max={k === 'zoom' ? 3 : 1} step="0.01" value={d.crop[k]} onChange={e => field('crop', { ...d.crop, [k]: Number(e.target.value) })} disabled={readonly}/></label>)}<p className="muted small">Historyczny herb na prawdziwym stroju pozostaje na fotografii.</p></div></details>}
        <details><summary>Opis posta i dostępność</summary><div className="form-group">{input('caption', 'Opis posta', { area: true, maxLength: 4000 })}{input('altText', 'Tekst alternatywny', { area: true })}{input('link', 'Link', { maxLength: 500 })}</div></details>
      </section>
      <section className={`preview-panel ${phone ? 'phone-preview' : ''}`}><div className="preview-toolbar"><span className="eyebrow">PODGLĄD / {formats[format as keyof typeof formats].width} × {formats[format as keyof typeof formats].height}</span><div><button className="icon-button" aria-label="Odśwież podgląd" disabled={busy || readonly} onClick={() => void action(async () => { setPreview(await send<Job>(`/projects/${initial.id}/jobs`, { kind: 'preview', format })); })}><RefreshCw size={17}/></button><button className={!phone ? 'selected icon-button' : 'icon-button'} aria-label="Duży podgląd" onClick={() => setPhone(false)}><Monitor size={17}/></button><button className={phone ? 'selected icon-button' : 'icon-button'} aria-label="Podgląd 360 pikseli" onClick={() => setPhone(true)}><Smartphone size={17}/></button><button className="icon-button" aria-label="Pełny ekran" onClick={() => setFullscreen(true)}><Eye size={17}/></button></div></div>{previewOptions}<div className="preview-stage">{image ? previewImage : <div className="preview-empty"><img src="/brand/sygnet2-kolor.svg" alt=""/><p>{preview?.status === 'failed' ? 'Popraw dane, aby zobaczyć podgląd' : readonly ? 'Projekt zarchiwizowany — podgląd niedostępny. Przywróć projekt lub utwórz kopię, aby wygenerować nowy.' : 'Składam Twój materiał…'}</p></div>}{preview && ['queued', 'running'].includes(preview.status) && <div className="preview-badge"><LoaderCircle size={14} className="spin"/>Odświeżam podgląd</div>}</div>{preview?.status === 'failed' && <p className="form-error render-error">{preview.error}</p>}<div className="preview-caption"><span>{readonly ? (image ? `Ostatni zapisany podgląd · rewizja ${preview?.revision}` : 'Projekt zarchiwizowany') : currentPreview ? `Podgląd rewizji ${preview?.revision}` : 'Podgląd roboczy · zmiany w toku'}</span>{outputs.length > 1 && <div>{outputs.map((_, i) => <button key={i} className={slide === i ? 'selected' : ''} onClick={() => setSlide(i)}>{i + 1}</button>)}</div>}<span>{phone ? 'Szerokość do 360 px' : 'Ten sam renderer co w eksporcie'}</span></div>{platform !== 'artwork' && <p className="social-preview-note">Symulacja interfejsu na telefonie. Wygląd kontrolek zależy od wersji aplikacji. Nakładki nie trafiają do eksportu.</p>}</section>
      <aside className="export-panel"><div className="panel-heading"><span className="eyebrow">FORMATY I KONTROLA</span><h2>Gotowe do publikacji.</h2></div><div className="format-list">{(publication && project.designVersion===DESIGN_VERSION ? designFormats(publication,project.visualStyle) : t.formats).map((f:string) => { const spec = formats[f as keyof typeof formats]; return <div key={f} className={format === f ? 'format-item selected' : 'format-item'}><label className="check-label"><input type="checkbox" checked={project.formats.includes(f)} disabled={readonly} onChange={e => { const values = e.target.checked ? [...project.formats, f] : project.formats.filter(x => x !== f); if (!values.length) return; change({ ...project, formats: values }); if (!values.includes(format)) setFormat(values[0]); }}/><span><b>{spec.label}</b><small>{spec.width} × {spec.height}</small></span></label><button className="icon-button" aria-label={`Podgląd ${spec.label}`} disabled={!project.formats.includes(f)} onClick={() => setFormat(f)}><Eye size={16}/></button></div>; })}</div>
        <div className="control-card"><ShieldCheck size={23}/><h3>Zgodność przed eksportem</h3><p>Układ, materiały i potwierdzone dane konkretnej rewizji.</p><span className={`status status-${templateStatus}`}>{templateStatus === 'approved' ? 'Szablon zatwierdzony' : 'Szablon do oceny'}</span>{false && !project.postType && t.status !== 'approved' && <button className="secondary" disabled={!currentPreview || busy} onClick={() => void action(async () => { await send(`/templates/${project.family}/approve`, { confirmed: true, previewJobId: preview!.id }); await reloadLibrary(); })}>Zatwierdzam rodzinę szablonów</button>}{project.postType && project.designVersion===DESIGN_VERSION && <><p className="design-format-status">{project.formats.map(f=>`${formats[f as keyof typeof formats].label}: ${designApproved(f)?'zatwierdzony':'do oceny'}`).join(' · ')}</p>{!designApproved(format) && <button className="secondary" disabled={busy || readonly || !currentPreview} onClick={()=>void action(async()=>{await send(`/designs/${project.postType}/${project.visualStyle}/${format}/approve`,{confirmed:true,previewJobId:preview!.id});await reloadLibrary();})}>Zatwierdzam tę kompozycję · {formats[format as keyof typeof formats].label}</button>}</>}<button className="secondary" disabled={busy || readonly || !currentPreview} onClick={() => setApprovalOpen(true)}>Potwierdź dane i wygląd</button><button className="text-button" disabled={busy} onClick={() => void action(async () => { await validate(); })}>Sprawdź eksport <ArrowLeft size={13} style={{ transform: 'rotate(180deg)' }}/></button>{report && <div className="validation-list" role="status">{report.valid ? <p className="valid"><Check size={16}/>Gotowe do eksportu</p> : report.errors.map((e, i) => <p key={i}><b>{e.field}</b>{e.message}</p>)}</div>}</div>
        <button className="primary export-button" disabled={busy || readonly || !currentPreview} onClick={() => void action(async () => { const v = await validate(); if (v.valid) setJob(await send<Job>(`/projects/${initial.id}/jobs`, { kind: 'export', idempotencyKey: crypto.randomUUID() })); })}><Download size={18}/>Generuj paczkę ZIP</button><p className="export-hint">PNG sRGB, opisy, oznaczenie AI i manifest.<br/>Wszystkie wybrane formaty.</p>
        {job && <div className="job-result" role="status"><b>{job.kind === 'export' ? 'Paczka publikacji' : 'Propozycja AI'}</b>{['queued', 'running'].includes(job.status) && <p><LoaderCircle size={15} className="spin"/> {job.status === 'queued' ? 'Czeka w kolejce…' : 'Trwa przygotowanie…'}</p>}{['failed', 'uncertain'].includes(job.status) && <p className="form-error">{job.error}</p>}{job.status === 'completed' && job.kind === 'export' && job.result?.files?.map(f => <ExportFile key={`${job.id}:${f.key}`} jobId={job.id} output={f} onError={setError}/>)}{job.result?.assetId && <p>Tło zapisane jako robocze. Otwórz Materiały, oceń obraz i zatwierdź.</p>}</div>}
        <details className="ai-panel"><summary><Sparkles size={16}/>Pomoc AI</summary><p className="muted small">AI proponuje treści i osobne tła. Zatwierdzasz je przed publikacją.</p><div className="budget-bar"><span style={{ width: `${budget ? Math.min(100, budget.usedMicros / Math.max(1, budget.limitMicros) * 100) : 0}%` }}/></div><small>{budget ? (budget.remainingMicros / 1e6).toFixed(2) : '10.00'} USD dostępne w tym miesiącu</small>{!budget?.configured && <p className="muted small">Klucz Gemini nie jest jeszcze skonfigurowany. Możesz tworzyć i eksportować materiały bez AI.</p>}<button className="secondary" disabled={!budget?.configured || busy || readonly} onClick={() => void action(async () => { setJob(await send<Job>(`/projects/${initial.id}/jobs`, { kind: 'ai-text' })); })}>Zaproponuj opis i alt</button><select aria-label="Rodzaj tła AI" value={brief} onChange={e => setBrief(e.target.value)}><option value="texture">Faktura papieru / farby</option><option value="background">Pusty parkiet</option><option value="still-life">Piłka na parkiecie</option></select><button className="secondary" disabled={!budget?.configured || busy || readonly} onClick={() => void action(async () => { setJob(await send<Job>(`/projects/${initial.id}/jobs`, { kind: 'ai-image', brief })); })}>Wygeneruj tło 2K</button><small>Rezerwacja: tekst ≤ 0,05 USD, tło ≤ 0,30 USD. Niepewne żądania zachowują rezerwację.</small></details>
        {!readonly && <button className="text-button archive-button" disabled={busy} onClick={() => void action(async () => { await send(`/projects/${initial.id}/archive`, { confirmed: true }); onClose(); })}>Archiwizuj projekt</button>}
      </aside>
    </div>
    {approvalOpen && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="approval-title"><h2 id="approval-title">Potwierdź rewizję {view.currentRevision}</h2><p>Sprawdziłem datę, godzinę, miejsce, rywala, wynik i nazwiska. Podgląd odpowiada zamierzonej publikacji. Korekty danych pozostają w Studio.</p><p className="muted">Każda kolejna zmiana będzie wymagała nowego potwierdzenia.</p><div className="modal-actions"><button className="secondary" onClick={() => setApprovalOpen(false)}>Wróć do edycji</button><button className="primary" disabled={busy || !currentPreview} onClick={() => void action(async () => { await send(`/projects/${initial.id}/approve`, { confirmed: true, expectedRevision: server.current.currentRevision, previewJobId: preview!.id }); setApprovalOpen(false); await validate(); })}>Potwierdzam</button></div></section></div>}
    {history && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="history-title"><div className="modal-heading"><h2 id="history-title">Historia projektu</h2><button className="icon-button" aria-label="Zamknij" onClick={() => setHistory(null)}>×</button></div>{history.map(r => <div className="history-row" key={r.number}><span>Rewizja {r.number}<small>{new Date(r.createdAt).toLocaleString('pl-PL')}</small></span><button className="secondary" disabled={readonly || r.number === view.currentRevision} onClick={() => { change(r.payload); setHistory(null); }}>Przywróć jako nową rewizję</button></div>)}</section></div>}
    {sourceDiff && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="diff-title"><h2 id="diff-title">Źródło zostało zaktualizowane</h2><p>Sprawdź różnice przed zastąpieniem danych w projekcie.</p><table><thead><tr><th>Pole</th><th>Projekt</th><th>Aktualne źródło</th></tr></thead><tbody>{Object.entries(sourceDiff.data).filter(([k, v]) => k in d && JSON.stringify(v) !== JSON.stringify((d as Record<string, unknown>)[k])).map(([k, v]) => <tr key={k}><td>{k}</td><td>{String((d as Record<string, unknown>)[k] ?? '')}</td><td>{String(v ?? '')}</td></tr>)}</tbody></table><div className="modal-actions"><button className="secondary" onClick={() => setSourceDiff(null)}>Zachowaj projekt</button><button className="primary" onClick={() => applySource(sourceDiff)}>Zastosuj aktualne dane</button></div></section></div>}
    {aiResult && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="ai-title"><div className="modal-heading"><h2 id="ai-title">Oceń propozycję AI</h2><button className="icon-button" aria-label="Zamknij" onClick={() => setAiResult(null)}>×</button></div><h3>Opis posta</h3><p>{aiResult.result?.caption}</p><h3>Krótka relacja</h3><p>{aiResult.result?.summary}</p><h3>Tekst alternatywny</h3><p>{aiResult.result?.altText}</p>{aiResult.revision !== view.currentRevision && <p className="form-error">Projekt zmienił się od wysłania żądania. Porównaj treść z aktualnymi danymi.</p>}<button className="primary" onClick={() => { change({ ...project, content: { ...d, caption: aiResult.result?.caption || d.caption, altText: aiResult.result?.altText || d.altText } }); setAiResult(null); }}>Zastosuj opis i tekst alternatywny</button></section></div>}
    {fullscreen && <div className="fullscreen-preview" role="dialog" aria-modal="true" aria-label="Pełnoekranowy podgląd"><button className="icon-button" aria-label="Zamknij podgląd" onClick={() => setFullscreen(false)}><X/></button>{previewOptions}{previewImage}{platform !== 'artwork' && <p className="social-preview-note">Symulacja interfejsu · nakładki nie trafiają do eksportu.</p>}</div>}
  </>;
}
