import { useState } from 'react';
import { Upload, ShieldCheck } from 'lucide-react';
import { api, send, assetUrl, API } from './api';
import type { Asset, Partner, Template } from './types';
const statuses: Record<string, string> = { draft: 'Do sprawdzenia', approved: 'Zatwierdzony', retired: 'Wycofany' };
export default function Library({ tab, assets, partners, templates, reload, onError }: { tab: string; assets: Asset[]; partners: Partner[]; templates: Template[]; reload: () => Promise<void>; onError: (s: string) => void }) {
  const [selected, setSelected] = useState<Asset | null>(null); const [uploading, setUploading] = useState(false); const [busy, setBusy] = useState(false);
  const [cmsPosts, setCmsPosts] = useState<{ id: string; title: string; media: { id: string; name: string }[] }[] | null>(null);
  const [partner, setPartner] = useState<Partner | null>(null);
  async function saveAsset(form: HTMLFormElement) {
    const f = new FormData(form); const metadata = { name: f.get('name'), kind: f.get('kind'), origin: f.get('origin'), people: f.get('people'), jerseyNumber: f.get('jerseyNumber'), consent: f.get('consent'), status: f.get('status') };
    setBusy(true); try { if (selected) await send(`/assets/${selected.id}`, metadata, 'PUT'); else { const body = new FormData(); body.set('file', f.get('file')!); body.set('metadata', JSON.stringify(metadata)); await api('/assets', { method: 'POST', body }); } setSelected(null); setUploading(false); await reload(); } catch (err) { onError((err as Error).message); } finally { setBusy(false); }
  }
  return <>
    {tab === 'assets' ? <><div className="section-title"><p className="muted">Prawdziwe zdjęcia. Sprawdzone prawa. Własne materiały.</p><div className="header-actions"><button className="secondary" onClick={async () => { try { setCmsPosts(await api('/sources/cms/news')); } catch (err) { onError((err as Error).message); } }}>Import z CMS</button><button className="secondary" onClick={() => setUploading(true)}><Upload size={17}/>Dodaj materiał</button></div></div><div className="asset-grid">{assets.map(a => <button key={a.id} className="asset-card" onClick={() => setSelected(a)}><img src={assetUrl(a.id)} alt={a.name}/><div><h3>{a.name}</h3><span className={`status status-${a.status}`}>{statuses[a.status]}</span>{a.provenance && <small>Ilustracja AI · wymaga oceny</small>}</div></button>)}</div>{!assets.length && <div className="empty"><Upload/><h3>Dodaj zdjęcia z parkietu</h3><p>JPEG, PNG, WebP, HEIC i gotowe wycięcia PNG.<br/>Materiały są prywatne; status publikacyjny ustalasz Ty.</p></div>}</> : <><section className="brand-rules"><img src="/brand/herb2-kolor.svg" alt="Znak 2.0"/><div><span className="eyebrow">AKTYWNY PAKIET · 2.0.2026-10-03</span><h2>ZNAKI, KTÓRE NAS ŁĄCZĄ.</h2><p>Barlow. Papier, farba i parkiet. Geometria 24° / 66°.<br/>Jeden poziom partnerów, kolejność alfabetyczna.</p><div className="swatches">{['#0B0B0B', '#EF1734', '#F7F6F2', '#F3F1EC', '#F4A816'].map(c => <span key={c}><i style={{ background: c }}/>{c}</span>)}</div></div></section><div className="section-title"><h2>Szablony</h2><span className="muted">Zatwierdzisz je w edytorze po ocenie podglądu</span></div><div className="template-statuses">{templates.map(t => <div key={t.id}><ShieldCheck size={19}/><b>{t.label}</b><span className={`status status-${t.status}`}>{statuses[t.status]}</span><button className="text-button" onClick={async () => { try { await send(`/templates/${t.id}/status`, { status: t.status === 'retired' ? 'draft' : 'retired' }); await reload(); } catch (err) { onError((err as Error).message); } }}>{t.status === 'retired' ? 'Przywróć roboczy' : 'Wycofaj'}</button></div>)}</div><div className="section-title"><h2>Rejestr partnerów</h2><button className="secondary" onClick={() => setPartner({ id: '', name: '', assetId: null, seedLogo: null, status: 'draft', contractNote: '' })}>Dodaj partnera</button></div><div className="partner-grid">{partners.map(p => <button key={p.id} onClick={() => setPartner(p)}><div className="partner-logo">{p.assetId ? <img src={assetUrl(p.assetId)} alt=""/> : p.seedLogo ? <img src={`${API}/partners/${encodeURIComponent(p.id)}/logo`} alt=""/> : <b>{p.name}</b>}</div><h3>{p.name}</h3><span className={`status status-${p.status}`}>{statuses[p.status]}</span></button>)}</div></>}
    {(selected || uploading) && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="asset-title"><div className="modal-heading"><h2 id="asset-title">{selected ? 'Sprawdź materiał' : 'Dodaj materiał'}</h2><button className="icon-button" aria-label="Zamknij" onClick={() => { setSelected(null); setUploading(false); }}>×</button></div>{selected && <img className="asset-detail" src={assetUrl(selected.id)} alt={selected.name}/>}<form onSubmit={e => { e.preventDefault(); void saveAsset(e.currentTarget); }}>
      {!selected && <label>Plik<input type="file" name="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" required/></label>}<label>Nazwa<input name="name" defaultValue={selected?.name} required maxLength={180}/></label><label>Rodzaj<select name="kind" defaultValue={selected?.kind || 'photo'} disabled={!!selected?.provenance}>{[['photo', 'Zdjęcie'], ['portrait', 'Portret'], ['cutout', 'Wycięcie PNG'], ['background', 'Tło'], ['logo', 'Logo partnera']].map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select>{selected?.provenance && <input type="hidden" name="kind" value="background"/>}</label><label>Pochodzenie / autor<input name="origin" defaultValue={selected?.origin} required maxLength={500}/></label><label>Osoby na zdjęciu<input name="people" defaultValue={selected?.people} maxLength={500}/></label><label>Numer stroju<input name="jerseyNumber" defaultValue={selected?.jerseyNumber} maxLength={3}/></label><label>Dopuszczalność publikacji<select name="consent" defaultValue={selected?.consent || 'unknown'}><option value="unknown">Nieustalona</option><option value="granted">Mam prawo do publikacji i wymagane zgody</option><option value="not_required">Zgoda osób nie jest wymagana; mam prawo do materiału</option><option value="withdrawn">Zgoda wycofana</option></select></label><label>Status<select name="status" defaultValue={selected?.status || 'draft'}><option value="draft">Do sprawdzenia</option><option value="approved">Zatwierdzam wygląd i dopuszczam publikację</option><option value="retired">Wycofany</option></select></label>{selected?.provenance && <details><summary>Pochodzenie AI</summary><p>{selected.provenance.model} · {selected.provenance.generatedAt} · {(selected.provenance.chargedMicros / 1e6).toFixed(3)} USD</p><p>{selected.provenance.prompt}</p></details>}<button className="primary" disabled={busy}>{busy ? 'Zapisywanie…' : 'Zapisz materiał'}</button></form></section></div>}
    {cmsPosts && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="cms-title"><div className="modal-heading"><h2 id="cms-title">Zdjęcia z opublikowanych treści</h2><button className="icon-button" aria-label="Zamknij" onClick={() => setCmsPosts(null)}>×</button></div><p className="muted">Import tworzy prywatną kopię w Studio. Potwierdź jej prawa i dopuszczalność publikacji w bibliotece.</p>{!cmsPosts.length && <p>Brak opublikowanych materiałów.</p>}{cmsPosts.map(p => <div className="history-row" key={p.id}><div><h3>{p.title}</h3>{p.media.map(m => <button key={m.id} className="secondary" disabled={busy} onClick={async () => { setBusy(true); try { await send('/assets/import-cms', { kind: 'news', documentId: p.id, mediaId: m.id }); await reload(); } catch (err) { onError((err as Error).message); } finally { setBusy(false); } }}>{m.name} · importuj</button>)}</div></div>)}</section></div>}
    {partner && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="partner-title"><div className="modal-heading"><h2 id="partner-title">Sprawdź partnera</h2><button className="icon-button" aria-label="Zamknij" onClick={() => setPartner(null)}>×</button></div><p className="muted">Potwierdź aktualną nazwę i znak. Bez logo Studio użyje plakietki tekstowej.</p><form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); try { await send(partner.id ? `/partners/${encodeURIComponent(partner.id)}` : '/partners', { name: f.get('name'), assetId: f.get('assetId') || null, status: f.get('status'), contractNote: f.get('contractNote') }, partner.id ? 'PUT' : 'POST'); setPartner(null); await reload(); } catch (err) { onError((err as Error).message); } finally { setBusy(false); } }}><label>Nazwa<input name="name" defaultValue={partner.name} required maxLength={180}/></label><label>Logo z biblioteki<select name="assetId" defaultValue={partner.assetId || ''}><option value="">{partner.seedLogo ? 'Logo z pakietu marki' : 'Plakietka tekstowa'}</option>{assets.filter(a => a.kind === 'logo').map(a => <option key={a.id} value={a.id}>{a.name} · {statuses[a.status]}</option>)}</select></label><label>Status<select name="status" defaultValue={partner.status}><option value="draft">Do sprawdzenia</option><option value="approved">Potwierdzam aktualność partnera i znaku</option><option value="retired">Wycofany</option></select></label><label>Warunki ekspozycji / uwagi<textarea name="contractNote" defaultValue={partner.contractNote} maxLength={1000}/></label><p className="muted">Wyjątek umowny wymaga zatwierdzonego szablonu obsługującego te warunki. Domyślny układ pozostaje równy i alfabetyczny.</p><button className="primary" disabled={busy}>Zapisz partnera</button></form></section></div>}
  </>;
}
