import { useEffect, useState } from 'react';
import { api } from './api';
import type { Season } from './seasons';
import type { Project } from './types';
type Snapshot={data:Record<string,unknown>;source:Project['content']['source']};
type Item={id:string;title?:string;opponent?:string;date?:string;name?:string};
export default function StatisticsImport({variant,seasons,season,setSeason,disabled,importData}:{variant:string;seasons:Season[];season:string;setSeason:(s:string)=>void;disabled:boolean;importData:(s:Snapshot)=>Promise<void>}) {
  const [items,setItems]=useState<Item[]>([]);const [selected,setSelected]=useState('');const [subjects,setSubjects]=useState<Item[]>([]);const [subject,setSubject]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);
  const kind=variant==='standings'?'standings':variant==='round'?'round':variant==='season'?'season':'match-statistics';
  const url=(id:string,subjectId='')=>`/sources/statistics?kind=${kind}&seasonId=${encodeURIComponent(season)}&id=${encodeURIComponent(id)}&subjectId=${encodeURIComponent(subjectId)}&view=${variant==='leaders'?'leaders':variant==='player'&&subjectId?'player':'team'}`;
  useEffect(()=>{let active=true;setSelected('');setSubject('');setSubjects([]);setItems([]);setError('');if(season&&['round','match-statistics'].includes(kind))api<Item[]>(kind==='round'?`/sources/rounds?seasonId=${encodeURIComponent(season)}`:`/sources/statistical-matches?seasonId=${encodeURIComponent(season)}`).then(r=>{if(active)setItems(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[season,kind]);
  useEffect(()=>{let active=true;setSubject('');setSubjects([]);if(variant==='player'&&selected)api<Snapshot>(url(selected)).then(r=>{if(active)setSubjects((r.data.subjects || []) as Item[]);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[selected,variant,season]);
  async function load(){setLoading(true);setError('');try{await importData(await api<Snapshot>(url(selected || season,subject)));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
  return <details open><summary>Statystyki z systemu</summary><div className="form-group"><label>Sezon<select disabled={disabled} value={season} onChange={e=>setSeason(e.target.value)}>{seasons.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label>{['round','match-statistics'].includes(kind)&&<label>{kind==='round'?'Kolejka':'Zakończony mecz'}<select disabled={disabled} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Wybierz…</option>{items.map(i=><option key={i.id} value={i.id}>{i.title || `${i.date?.slice(0,10)} · ${i.opponent}`}</option>)}</select></label>}{variant==='player'&&<label>Zawodnik w tym meczu<select value={subject} disabled={disabled || !subjects.length} onChange={e=>setSubject(e.target.value)}><option value="">Wybierz zawodnika…</option>{subjects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<button className="secondary" disabled={disabled || loading || !season || (['round','match-statistics'].includes(kind)&&!selected) || (variant==='player'&&!subject)} onClick={()=>void load()}>{loading?'Pobieranie…':'Importuj publiczne dane'}</button><small>Publiczne dane KALK. Brak wartości pozostaje brakiem danych. Możesz też uzupełnić tabelę ręcznie.</small>{error&&<p role="alert">{error}</p>}</div></details>;
}
