import { z } from 'zod';
import { projectSchema } from '../../backend/studio/contracts.js';
export type Project = z.infer<typeof projectSchema>;
export type View = { id: string; name: string; family: string; status: string; currentRevision: number; payload: Project; revision: { id: string; number: number; contentHash: string; createdAt: string }; jobs?: Job[]; updatedAt: string };
export type Job = { id: string; revision: number; status: string; kind: string; error?: string; result?: { files?: Output[]; expiresAt?: string; revision?: number; caption?: string; summary?: string; altText?: string; assetId?: string } };
export type Output = { key: string; name: string; mime: string; width?: number; height?: number };
export type Asset = { id: string; name: string; kind: string; status: string; origin: string; people: string; jerseyNumber: string; consent: string; provenance?: { prompt: string; model: string; generatedAt: string; chargedMicros: number } };
export type Partner = { id: string; name: string; assetId: string | null; seedLogo: string | null; status: string; contractNote: string };
export type Template = { id: string; family?: string; label: string; description: string; variants: string[]; layouts: string[]; formats: string[]; version: string; status: string };
export type Report = { valid: boolean; errors: { field: string; message: string }[] };
export type Budget = { configured: boolean; remainingMicros: number; usedMicros: number; limitMicros: number; month: string };
