-- AlterTable
ALTER TABLE "LeagueTeam" ADD COLUMN IF NOT EXISTS "logoUrl" TEXT;
ALTER TABLE "LeagueTeam" ADD COLUMN IF NOT EXISTS "form" TEXT;
ALTER TABLE "LeagueTeam" ADD COLUMN IF NOT EXISTS "streak" TEXT;
